# Powerlevel10k configuration for duke pan's i3 rice
# Generated by `p10k configure` and customized for Catppuccin Mocha

# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # Unset all configuration options.
  unset POWERLEVEL9K_*

  # Left prompt segments
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    os_icon                 # OS identifier
    user                    # Username (duke pan)
    dir                     # Current directory
    vcs                     # Git repository status
    virtualenv              # Python virtual environment
    nodeenv                 # Node.js environment
    docker_machine          # Docker machine
    kubecontext             # Kubernetes context
    newline                 # Line break
    prompt_char             # Prompt character
  )

  # Right prompt segments
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status                  # Exit code of last command
    command_execution_time  # Duration of last command
    background_jobs         # Background jobs indicator
    direnv                  # Direnv status
    asdf                    # ASDF version manager
    pyenv                   # Python version from pyenv
    nvm                     # Node.js version from nvm
    rbenv                   # Ruby version from rbenv
    terraform               # Terraform workspace
    aws                     # AWS profile
    gcloud                  # Google Cloud configuration
    context                 # User@hostname
    nordvpn                 # NordVPN connection status
    ranger                  # Ranger shell
    vim_shell               # Vim shell indicator
    nix_shell               # Nix shell
    vi_mode                 # Vi editing mode
    todo                    # Todo items count
    timewarrior             # Timewarrior tracking
    taskwarrior             # Taskwarrior tasks
    time                    # Current time
    battery                 # Battery level and status
    wifi                    # WiFi status
    load                    # System load
    ram                     # RAM usage
    disk_usage              # Disk usage
  )

  # Basic style options
  typeset -g POWERLEVEL9K_BACKGROUND=                            # transparent background
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=  # no surrounding whitespace
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '  # separate segments with a space
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=        # no end-of-line symbol
  typeset -g POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION='${P9K_VISUAL_IDENTIFIER// }'

  # Catppuccin Mocha Colors
  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=110                # Catppuccin Lavender
  typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=                   # transparent
  typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION='🐧'        # Linux penguin

  # User segment - duke pan customization
  typeset -g POWERLEVEL9K_USER_FOREGROUND=147                   # Catppuccin Mauve
  typeset -g POWERLEVEL9K_USER_BACKGROUND=                      # transparent
  typeset -g POWERLEVEL9K_USER_TEMPLATE='👑 duke pan'           # Custom username with crown
  typeset -g POWERLEVEL9K_USER_DEFAULT_FOREGROUND=147
  typeset -g POWERLEVEL9K_USER_ROOT_FOREGROUND=203              # Catppuccin Red
  typeset -g POWERLEVEL9K_USER_ROOT_TEMPLATE='⚡ root'          # Root with lightning

  # Directory segment
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=116                    # Catppuccin Green
  typeset -g POWERLEVEL9K_DIR_BACKGROUND=                       # transparent
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=116
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=116
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
  typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=
  typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=80
  typeset -g POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=false
  typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
  typeset -g POWERLEVEL9K_SHORTEN_FOLDER_MARKER='(\.git|\.svn|\.hg|\.bzr)'
  typeset -g POWERLEVEL9K_DIR_CLASSES=(
    '~/Projects(|/*)'  PROJECT  '💼'
    '~/Downloads(|/*)'  DOWNLOAD  '📥'
    '~/.config(|/*)'   CONFIG   '⚙️'
    '/etc(|/*)'        ETC      '🔧'
    '/var/log(|/*)'    LOG      '📋'
  )

  # VCS (Git) segment
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uF126 '             # Git branch icon
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=116              # Catppuccin Green
  typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=                 # transparent
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=215         # Catppuccin Yellow
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=209           # Catppuccin Peach
  typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=
  typeset -g POWERLEVEL9K_VCS_STAGED_FOREGROUND=117             # Catppuccin Teal
  typeset -g POWERLEVEL9K_VCS_STAGED_BACKGROUND=
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=203         # Catppuccin Red
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND=
  typeset -g POWERLEVEL9K_VCS_COMMITS_AHEAD_MAX_NUM=5
  typeset -g POWERLEVEL9K_VCS_COMMITS_BEHIND_MAX_NUM=5

  # Prompt character
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=147  # Catppuccin Mauve
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=203  # Catppuccin Red
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='V'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION='▶'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=

  # Status segment
  typeset -g POWERLEVEL9K_STATUS_EXTENDED_STATES=true
  typeset -g POWERLEVEL9K_STATUS_OK=false
  typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=116              # Catppuccin Green
  typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=203           # Catppuccin Red
  typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=203
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_BACKGROUND=
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=203
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_BACKGROUND=

  # Command execution time
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=215 # Catppuccin Yellow
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'

  # Background jobs
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=117        # Catppuccin Teal
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=

  # Time segment
  typeset -g POWERLEVEL9K_TIME_FOREGROUND=110                   # Catppuccin Lavender
  typeset -g POWERLEVEL9K_TIME_BACKGROUND=
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{🕐 %H:%M:%S}'
  typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=true

  # Battery segment
  typeset -g POWERLEVEL9K_BATTERY_LOW_THRESHOLD=20
  typeset -g POWERLEVEL9K_BATTERY_LOW_FOREGROUND=203            # Catppuccin Red
  typeset -g POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND=215      # Catppuccin Yellow
  typeset -g POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND=116       # Catppuccin Green
  typeset -g POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND=147  # Catppuccin Mauve
  typeset -g POWERLEVEL9K_BATTERY_STAGES='\uf58d\uf579\uf57a\uf57b\uf57c\uf57d\uf57e\uf57f\uf580\uf581\uf578'
  typeset -g POWERLEVEL9K_BATTERY_VERBOSE=false

  # Context (user@host)
  typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=147                # Catppuccin Mauve
  typeset -g POWERLEVEL9K_CONTEXT_BACKGROUND=
  typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='👑 duke pan@%m'
  typeset -g POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND=147
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=203           # Catppuccin Red

  # Virtual environments
  typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=117             # Catppuccin Teal
  typeset -g POWERLEVEL9K_VIRTUALENV_BACKGROUND=
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=true
  typeset -g POWERLEVEL9K_PYENV_FOREGROUND=117
  typeset -g POWERLEVEL9K_PYENV_BACKGROUND=
  typeset -g POWERLEVEL9K_NODENV_FOREGROUND=116                 # Catppuccin Green
  typeset -g POWERLEVEL9K_NODENV_BACKGROUND=
  typeset -g POWERLEVEL9K_NVM_FOREGROUND=116
  typeset -g POWERLEVEL9K_NVM_BACKGROUND=

  # Docker
  typeset -g POWERLEVEL9K_DOCKER_MACHINE_FOREGROUND=117        # Catppuccin Teal
  typeset -g POWERLEVEL9K_DOCKER_MACHINE_BACKGROUND=

  # Kubernetes
  typeset -g POWERLEVEL9K_KUBECONTEXT_FOREGROUND=117            # Catppuccin Teal
  typeset -g POWERLEVEL9K_KUBECONTEXT_BACKGROUND=
  typeset -g POWERLEVEL9K_KUBECONTEXT_SHOW_DEFAULT_NAMESPACE=true

  # Terraform
  typeset -g POWERLEVEL9K_TERRAFORM_FOREGROUND=147              # Catppuccin Mauve
  typeset -g POWERLEVEL9K_TERRAFORM_BACKGROUND=

  # AWS
  typeset -g POWERLEVEL9K_AWS_FOREGROUND=209                    # Catppuccin Peach
  typeset -g POWERLEVEL9K_AWS_BACKGROUND=

  # Google Cloud
  typeset -g POWERLEVEL9K_GCLOUD_FOREGROUND=117                # Catppuccin Teal
  typeset -g POWERLEVEL9K_GCLOUD_BACKGROUND=

  # WiFi segment
  typeset -g POWERLEVEL9K_WIFI_FOREGROUND=117                  # Catppuccin Teal
  typeset -g POWERLEVEL9K_WIFI_BACKGROUND=

  # Load segment
  typeset -g POWERLEVEL9K_LOAD_WHICH=5
  typeset -g POWERLEVEL9K_LOAD_NORMAL_FOREGROUND=116           # Catppuccin Green
  typeset -g POWERLEVEL9K_LOAD_WARNING_FOREGROUND=215         # Catppuccin Yellow
  typeset -g POWERLEVEL9K_LOAD_CRITICAL_FOREGROUND=203        # Catppuccin Red

  # RAM segment
  typeset -g POWERLEVEL9K_RAM_FOREGROUND=147                   # Catppuccin Mauve
  typeset -g POWERLEVEL9K_RAM_BACKGROUND=

  # Disk usage segment
  typeset -g POWERLEVEL9K_DISK_USAGE_NORMAL_FOREGROUND=116     # Catppuccin Green
  typeset -g POWERLEVEL9K_DISK_USAGE_WARNING_FOREGROUND=215   # Catppuccin Yellow
  typeset -g POWERLEVEL9K_DISK_USAGE_CRITICAL_FOREGROUND=203  # Catppuccin Red

  # Todo segment
  typeset -g POWERLEVEL9K_TODO_FOREGROUND=215                  # Catppuccin Yellow
  typeset -g POWERLEVEL9K_TODO_BACKGROUND=

  # Vi mode
  typeset -g POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND=116        # Catppuccin Green
  typeset -g POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND=203        # Catppuccin Red
  typeset -g POWERLEVEL9K_VI_MODE_VISUAL_FOREGROUND=215        # Catppuccin Yellow
  typeset -g POWERLEVEL9K_VI_MODE_REPLACE_FOREGROUND=209       # Catppuccin Peach

  # Transient prompt
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  # Multiline
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX=
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX=
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX=

  # Connect left and right prompts
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR='─'
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_BACKGROUND=
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_GAP_BACKGROUND=
  if [[ $POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR != ' ' ]]; then
    typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=244
    typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_FIRST_SEGMENT_END_SYMBOL='%{%}'
    typeset -g POWERLEVEL9K_FILL_BG=$POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_BACKGROUND
    typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_EXPANSION='${P9K_GAP_CHAR// /${(pl.$((COLUMNS-P9K_GAP_CHAR_LEN))..${P9K_GAP_CHAR:- }.):-}}'
  fi

  # Frame
  typeset -g POWERLEVEL9K_SHOW_RULER=false
  typeset -g POWERLEVEL9K_RULER_CHAR='─'
  typeset -g POWERLEVEL9K_RULER_FOREGROUND=244

  # Enable special PowerLevel10k extensions
  typeset -g POWERLEVEL9K_DISABLE_GITSTATUS=false
  typeset -g POWERLEVEL9K_LEGACY_ICON_SPACING=false

  # Segment separators
  typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
  typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
  typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
  typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=' '
  typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=' '

  # duke pan's custom segments
  typeset -g POWERLEVEL9K_CUSTOM_DUKE_SHOW_ON_COMMAND='duke_info'
  typeset -g POWERLEVEL9K_CUSTOM_DUKE_FOREGROUND=147           # Catppuccin Mauve
  typeset -g POWERLEVEL9K_CUSTOM_DUKE_BACKGROUND=
  
  # Rice status segment
  typeset -g POWERLEVEL9K_CUSTOM_RICE_SHOW_ON_COMMAND='rice_show'
  typeset -g POWERLEVEL9K_CUSTOM_RICE_FOREGROUND=116           # Catppuccin Green
  typeset -g POWERLEVEL9K_CUSTOM_RICE_BACKGROUND=
}

# Restore previous options
(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
